[tool.poetry]
name = "creator"
version = "0.1.0"
description = ""
authors = ["vijayantajain <vijayantajain@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dynaconf = "^3.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
